/**
 * @file modbus_driver_config.h
 * @author niwciu (niwciu@gmail.com)
 * @brief Modbus master driver hardware configuration for STM32G474RE.
 *        USART1: PA9=TX (AF7), PA10=RX (AF7), PA12=DE (AF7, HW control)
 *        TIM7:   APB1
 *        DMA1_Channel1 via DMAMUX1_Channel0, USART1_TX resource = 25
 * @version 1.0.0
 * @date 2025-08-31
 *
 * @copyright Copyright (c) 2025
 *
 */
#pragma once

#include "stm32g474xx.h"

#define OFF 0
#define ON  1
#define LOW  0
#define HIGH 1

#define MASTER_USE_DMA              ON
#define MASTER_USART_DE_HW_CONTROLL ON

/** USART1 — APB2 */
#define MODBUS_MASTER_USART         (USART1)
#define MODBUS_MASTER_USART_CLK     APB2ENR
#define MODBUS_MASTER_USART_CLK_EN  (RCC_APB2ENR_USART1EN)
#define MODBUS_MASTER_USART_CLK_FREQ 64000000UL
#define MODBUS_MASTER_USART_IRQN    USART1_IRQn
#define MODBUS_MASTER_USART_IRQHandler USART1_IRQHandler
#define MODBUS_MASTER_USART_IRQ_PRIORITY 10

#if MASTER_USE_DMA == ON
#define MODBUS_MASTER_DMA           DMA1
#define MODBUS_MASTER_DMA_IRQN      DMA1_Channel1_IRQn
#define MODBUS_MASTER_DMA_IRQHandler DMA1_Channel1_IRQHandler
#define MODBUS_MASTER_DMA_chanel    DMA1_Channel1
#define MODBUS_MASTER_DMA_ISR_TCIF  DMA_ISR_TCIF1
#define MODBUS_MASTER_DMA_ISR_TEIF  DMA_ISR_TEIF1

/** DMAMUX1_Channel0 drives DMA1_Channel1; USART1_TX request ID = 25 */
#define MODBUS_MASTER_USART_TX_RESOURCE 25
#define MODBUS_MASTER_DMAMUX_Chanel (DMAMUX1_Channel0)

/** DMA clock on AHB1 (G474 differs from G070 AHBENR) */
#define MODBUS_MASTER_DMA_CLK_REG   AHB1ENR
#define MODBUS_MASTER_DMA_CLK_EN    RCC_AHB1ENR_DMA1EN
#endif

/** GPIO ports — PA9/PA10/PA12 all on GPIOA */
#define MODBUS_MASTER_USART_RX_TX_PORT (GPIOA)
#define MODBUS_MASTER_USART_DE_PORT    (GPIOA)

/** GPIO mode bits — AF mode (10b) */
#define MODBUS_MASTER_USART_RX_MODE     (GPIO_MODER_MODE10_1) // PA10, AF
#define MODBUS_MASTER_USART_TX_MODE     (GPIO_MODER_MODE9_1)  // PA9,  AF
#if MASTER_USART_DE_HW_CONTROLL == ON
#define MODBUS_MASTER_USART_DE_MODE     (GPIO_MODER_MODE12_1) // PA12, AF
#else
#define MODBUS_MASTER_USART_DE_MODE     (GPIO_MODER_MODE12_0) // PA12, output
#endif

#define MODBUS_MASTER_USART_RX_MODE_Msk (GPIO_MODER_MODE10)
#define MODBUS_MASTER_USART_TX_MODE_Msk (GPIO_MODER_MODE9)
#define MODBUS_MASTER_USART_DE_MODE_Msk (GPIO_MODER_MODE12)

/** AF register masks — PA9/PA10/PA12 are in AFRH (pins 8–15) */
#define MODBUS_MASTER_USART_RX_AF_Msk   (GPIO_AFRH_AFSEL10)
#define MODBUS_MASTER_USART_TX_AF_Msk   (GPIO_AFRH_AFSEL9)
#if MASTER_USART_DE_HW_CONTROLL == ON
#define MODBUS_MASTER_USART_DE_AF_Msk   (GPIO_AFRH_AFSEL12)
#endif

/** AF7 values for USART1 on PA9/PA10/PA12 */
#define MODBUS_MASTER_USART_RX_AF  (GPIO_AFRH_AFSEL10_0 | GPIO_AFRH_AFSEL10_1 | GPIO_AFRH_AFSEL10_2)
#define MODBUS_MASTER_USART_TX_AF  (GPIO_AFRH_AFSEL9_0  | GPIO_AFRH_AFSEL9_1  | GPIO_AFRH_AFSEL9_2)
#if MASTER_USART_DE_HW_CONTROLL == ON
#define MODBUS_MASTER_USART_DE_AF  (GPIO_AFRH_AFSEL12_0 | GPIO_AFRH_AFSEL12_1 | GPIO_AFRH_AFSEL12_2)
#endif

/** All pins PA9/PA10/PA12 are in AFRH */
#define MODBUS_MASTER_USART_RX_TX_AF_REG (HIGH)
#if MASTER_USART_DE_HW_CONTROLL == ON
#define MODBUS_MASTER_USART_DE_AF_REG    (HIGH)
#endif

// additional defines for manual DE control
#if MASTER_USART_DE_HW_CONTROLL == OFF
#define MODBUS_MASTER_USART_DE_PUPDR     GPIO_PUPDR_PUPD12_0
#define MODBUS_MASTER_USART_DE_PUPDR_Msk GPIO_PUPDR_PUPD12_Msk
#define MODBUS_MASTER_USART_DE_RESET_PIN GPIO_BSRR_BR12
#define MODBUS_MASTER_USART_DE_SET_PIN   GPIO_BSRR_BS12
#endif

/** GPIO clock enable — G474 uses AHB2 for GPIO */
#define MODBUS_MASTER_USART_GPIO_RX_TX_CLK_EN (RCC_AHB2ENR_GPIOAEN)
#define MODBUS_MASTER_USART_GPIO_DE_CLK_EN    (RCC_AHB2ENR_GPIOAEN)
#define MODBUS_MASTER_GPIO_CLK_REG             AHB2ENR

/** TIM7 — APB1, IRQ shared with DAC on some G4 variants */
#define MODBUS_MASTER_TIMER          (TIM7)
#define MODBUS_MASTER_TIMER_APBENR   (RCC->APB1ENR1)
#define MODBUS_MASTER_TIMER_CLK_EN   (RCC_APB1ENR1_TIM7EN)
#define MODBUS_MASTER_TIMER_CLK_FREQ  64000000UL
#define MODBUS_MASTER_TIMER_IRQN      TIM7_DAC_IRQn
#define MODBUS_MASTER_TIMER_IRQHandler TIM7_DAC_IRQHandler
#define MODBUS_MASTER_TIMER_IRQ_PRIORITY 10
