/**
 * @file modbus_slave_driver_config_usart3.h
 * @author niwciu (niwciu@gmail.com)
 * @brief Header file with defines that speed up modbus slave driver configuration
 *        specially when porting driver to different USARTs and Timers.
 *        STM32G474RE — USART3 variant.
 *        USART3: PB10=TX (AF7), PB11=RX (AF7), PB14=DE (AF7)
 *        TIM6: APB1, IRQ shared with DAC
 *        DMA1_Channel1 via DMAMUX1_Channel0, USART3_TX resource=28

 * @version 0.0.1
 * @date 2025-08-31
 *
 * @copyright Copyright (c) 2025
 *
 */
#pragma once

#include "stm32g474xx.h"

#define OFF 0
#define ON 1
#define LOW 0
#define HIGH 1

#define SLAVE_USE_DMA ON
#define SLAVE_USART_DE_HW_CONTROLL ON

/** modbus USART configuration*/
#define MODBUS_SLAVE_USART (USART3)
#define MODBUS_SLAVE_USART_CLK APB1ENR1
#define MODBUS_SLAVE_USART_CLK_EN (RCC_APB1ENR1_USART3EN)
#define MODBUS_SLAVE_USART_CLK_FREQ 64000000UL
#define MODBUS_SLAVE_USART_IRQN USART3_IRQn
#define MODBUS_SLAVE_USART_IRQHandler USART3_IRQHandler
#define MODBUS_SLAVE_USART_IRQ_PRIORITY 10

#if SLAVE_USE_DMA == ON
#define MODBUS_SLAVE_DMA DMA1
#define MODBUS_SLAVE_DMA_IRQN DMA1_Channel1_IRQn
#define MODBUS_SLAVE_DMA_IRQHandler DMA1_Channel1_IRQHandler
#define MODBUS_SLAVE_DMA_chanel DMA1_Channel1
#define MODBUS_SLAVE_DMA_ISR_TCIF DMA_ISR_TCIF1
#define MODBUS_SLAVE_DMA_ISR_TEIF DMA_ISR_TEIF1

#define USART1_TX_RESOURCE 25
#define USART2_TX_RESOURCE 26
#define USART3_TX_RESOURCE 28
#define MODBUS_SLAVE_USART_TX_RESOURCE USART3_TX_RESOURCE

#define MODBUS_SLAVE_DMAMUX_Chanel (DMAMUX1_Channel0)

/** DMA clock on AHB1 (G474 differs from G070 AHBENR) */
#define MODBUS_SLAVE_DMA_CLK_REG AHB1ENR
#define MODBUS_SLAVE_DMA_CLK_EN  RCC_AHB1ENR_DMA1EN
#endif

/** GPIO ports — PB10/PB11/PB14 all on GPIOB */
#define MODBUS_SLAVE_USART_RX_TX_PORT (GPIOB)
#define MODBUS_SLAVE_USART_DE_PORT (GPIOB)


#define MODBUS_SLAVE_USART_RX_MODE (GPIO_MODER_MODE11_1) // af mode
#define MODBUS_SLAVE_USART_TX_MODE (GPIO_MODER_MODE10_1) // af mode
#if SLAVE_USART_DE_HW_CONTROLL == ON
#define MODBUS_SLAVE_USART_DE_MODE (GPIO_MODER_MODE14_1) // af mode
#else
#define MODBUS_SLAVE_USART_DE_MODE (GPIO_MODER_MODE14_0) // general purpose output mode
#endif

#define MODBUS_SLAVE_USART_RX_MODE_Msk (GPIO_MODER_MODE11)
#define MODBUS_SLAVE_USART_TX_MODE_Msk (GPIO_MODER_MODE10)
#define MODBUS_SLAVE_USART_DE_MODE_Msk (GPIO_MODER_MODE14)

/** AF register masks — PB10/PB11/PB14 in AFRH (pins 8-15) */
#define MODBUS_SLAVE_USART_RX_AF_Msk (GPIO_AFRH_AFSEL11)
#define MODBUS_SLAVE_USART_TX_AF_Msk (GPIO_AFRH_AFSEL10)
#if SLAVE_USART_DE_HW_CONTROLL == ON
#define MODBUS_SLAVE_USART_DE_AF_Msk (GPIO_AFRH_AFSEL14)
#endif

/** AF7 values for USART3 on PB10/PB11/PB14 */
#define MODBUS_SLAVE_USART_RX_AF (GPIO_AFRH_AFSEL11_0 | GPIO_AFRH_AFSEL11_1 | GPIO_AFRH_AFSEL11_2)
#define MODBUS_SLAVE_USART_TX_AF (GPIO_AFRH_AFSEL10_0 | GPIO_AFRH_AFSEL10_1 | GPIO_AFRH_AFSEL10_2)
#if SLAVE_USART_DE_HW_CONTROLL == ON
#define MODBUS_SLAVE_USART_DE_AF (GPIO_AFRH_AFSEL14_0 | GPIO_AFRH_AFSEL14_1 | GPIO_AFRH_AFSEL14_2)
#endif

/** All pins PB10/PB11/PB14 are in AFRH */
#define MODBUS_SLAVE_USART_RX_TX_AF_REG (HIGH)
#if SLAVE_USART_DE_HW_CONTROLL == ON
#define MODBUS_SLAVE_USART_DE_AF_REG (HIGH)
#endif

// additionaly defines for manual DE controll
#if SLAVE_USART_DE_HW_CONTROLL == OFF
#define MODBUS_SLAVE_USART_DE_PUPDR        GPIO_PUPDR_PUPD14_0
#define MODBUS_SLAVE_USART_DE_PUPDR_Msk    GPIO_PUPDR_PUPD14_Msk

#define MODBUS_SLAVE_USART_DE_RESET_PIN	GPIO_BSRR_BR14
#define MODBUS_SLAVE_USART_DE_SET_PIN		GPIO_BSRR_BS14
#endif

/** GPIO clock enable — G474 uses AHB2 for GPIO (vs G070 IOPENR) */
#define MODBUS_SLAVE_USART_GPIO_RX_TX_CLK_EN (RCC_AHB2ENR_GPIOBEN)
#define MODBUS_SLAVE_USART_GPIO_DE_CLK_EN (RCC_AHB2ENR_GPIOBEN)
#define MODBUS_SLAVE_GPIO_CLK_REG AHB2ENR


/** modbus Timer configuration — TIM6 APB1, IRQ shared with DAC */
#define MODBUS_SLAVE_TIMER (TIM6)
#define MODBUS_SLAVE_TIMER_APBENR (RCC->APB1ENR1)
#define MODBUS_SLAVE_TIMER_CLK_EN (RCC_APB1ENR1_TIM6EN)
#define MODBUS_SLAVE_TIMER_CLK_FREQ 64000000UL
#define MODBUS_SLAVE_TIMER_IRQN TIM6_DAC_IRQn
#define MODBUS_SLAVE_TIMER_IRQHandler TIM6_DAC_IRQHandler
#define MODBUS_SLAVE_TIMER_IRQ_PRIORITY 10
