/**
 * @file modbus_master_driver_config_uart4.h
 * @author niwciu (niwciu@gmail.com)
 * @brief Header file with defines that speed up modbus master driver configuration
 *        specially when porting driver to different USARTs and Timers.
 *        STM32G474RE — UART4 variant.
 *        UART4: PC10=TX (AF5), PC11=RX (AF5), PB7=DE (AF5)
 *        TIM7: APB1, IRQ shared with DAC
 *        DMA1_Channel4 via DMAMUX1_Channel3, UART4_TX resource=30
 *        NOTE: Verify DMAMUX request ID for UART4_TX in RM0440 Table 91.

 * @version 0.0.1
 * @date 2025-08-31
 *
 * @copyright Copyright (c) 2025
 *
 */
#pragma once

#include "stm32g474xx.h"

#define OFF 0
#define ON 1
#define LOW 0
#define HIGH 1

#define MASTER_USE_DMA ON
#define MASTER_USART_DE_HW_CONTROLL ON

/** modbus USART configuration*/
#define MODBUS_MASTER_USART (UART4)
#define MODBUS_MASTER_USART_CLK APB1ENR1
#define MODBUS_MASTER_USART_CLK_EN (RCC_APB1ENR1_UART4EN)
#define MODBUS_MASTER_USART_CLK_FREQ 64000000UL
#define MODBUS_MASTER_USART_IRQN UART4_IRQn
#define MODBUS_MASTER_USART_IRQHandler UART4_IRQHandler
#define MODBUS_MASTER_USART_IRQ_PRIORITY 10

#if MASTER_USE_DMA == ON
#define MODBUS_MASTER_DMA DMA1
#define MODBUS_MASTER_DMA_IRQN DMA1_Channel4_IRQn
#define MODBUS_MASTER_DMA_IRQHandler DMA1_Channel4_IRQHandler
#define MODBUS_MASTER_DMA_chanel DMA1_Channel4
#define MODBUS_MASTER_DMA_ISR_TCIF DMA_ISR_TCIF4
#define MODBUS_MASTER_DMA_ISR_TEIF DMA_ISR_TEIF4

#define USART1_TX_RESOURCE 25
#define USART2_TX_RESOURCE 26
#define USART3_TX_RESOURCE 28
#define UART4_TX_RESOURCE  30  // verify in RM0440 Table 91
#define UART5_TX_RESOURCE  32  // verify in RM0440 Table 91
#define MODBUS_MASTER_USART_TX_RESOURCE UART4_TX_RESOURCE

#define MODBUS_MASTER_DMAMUX_Chanel (DMAMUX1_Channel3)

/** DMA clock on AHB1 (G474 differs from G070 AHBENR) */
#define MODBUS_MASTER_DMA_CLK_REG AHB1ENR
#define MODBUS_MASTER_DMA_CLK_EN  RCC_AHB1ENR_DMA1EN
#endif

/** GPIO ports — PC10/PC11 on GPIOC, PB7 (DE) on GPIOB */
#define MODBUS_MASTER_USART_RX_TX_PORT (GPIOC)
#define MODBUS_MASTER_USART_DE_PORT (GPIOB)


#define MODBUS_MASTER_USART_RX_MODE (GPIO_MODER_MODE11_1) // af mode
#define MODBUS_MASTER_USART_TX_MODE (GPIO_MODER_MODE10_1) // af mode
#if MASTER_USART_DE_HW_CONTROLL == ON
#define MODBUS_MASTER_USART_DE_MODE (GPIO_MODER_MODE7_1) // af mode
#else
#define MODBUS_MASTER_USART_DE_MODE (GPIO_MODER_MODE7_0) // general purpose output mode
#endif

#define MODBUS_MASTER_USART_RX_MODE_Msk (GPIO_MODER_MODE11)
#define MODBUS_MASTER_USART_TX_MODE_Msk (GPIO_MODER_MODE10)
#define MODBUS_MASTER_USART_DE_MODE_Msk (GPIO_MODER_MODE7)

/** AF register masks — PC10/PC11 in AFRH, PB7 (DE) in AFRL */
#define MODBUS_MASTER_USART_RX_AF_Msk (GPIO_AFRH_AFSEL11)
#define MODBUS_MASTER_USART_TX_AF_Msk (GPIO_AFRH_AFSEL10)
#if MASTER_USART_DE_HW_CONTROLL == ON
#define MODBUS_MASTER_USART_DE_AF_Msk (GPIO_AFRL_AFSEL7)
#endif

/** AF5 values for UART4 on PC10/PC11/PB7 */
#define MODBUS_MASTER_USART_RX_AF (GPIO_AFRH_AFSEL11_0 | GPIO_AFRH_AFSEL11_2)
#define MODBUS_MASTER_USART_TX_AF (GPIO_AFRH_AFSEL10_0 | GPIO_AFRH_AFSEL10_2)
#if MASTER_USART_DE_HW_CONTROLL == ON
#define MODBUS_MASTER_USART_DE_AF (GPIO_AFRL_AFSEL7_0 | GPIO_AFRL_AFSEL7_2)
#endif

/** PC10/PC11 in AFRH, PB7 (DE) in AFRL */
#define MODBUS_MASTER_USART_RX_TX_AF_REG (HIGH)
#if MASTER_USART_DE_HW_CONTROLL == ON
#define MODBUS_MASTER_USART_DE_AF_REG (LOW)
#endif

// additionaly defines for manual DE controll
#if MASTER_USART_DE_HW_CONTROLL == OFF
#define MODBUS_MASTER_USART_DE_PUPDR        GPIO_PUPDR_PUPD7_0
#define MODBUS_MASTER_USART_DE_PUPDR_Msk    GPIO_PUPDR_PUPD7_Msk

#define MODBUS_MASTER_USART_DE_RESET_PIN	GPIO_BSRR_BR7
#define MODBUS_MASTER_USART_DE_SET_PIN		GPIO_BSRR_BS7
#endif

/** GPIO clock enable — G474 uses AHB2 for GPIO */
#define MODBUS_MASTER_USART_GPIO_RX_TX_CLK_EN (RCC_AHB2ENR_GPIOCEN)
#define MODBUS_MASTER_USART_GPIO_DE_CLK_EN (RCC_AHB2ENR_GPIOBEN)
#define MODBUS_MASTER_GPIO_CLK_REG AHB2ENR


/** modbus Timer configuration — TIM7 APB1, IRQ shared with DAC */
#define MODBUS_MASTER_TIMER (TIM7)
#define MODBUS_MASTER_TIMER_APBENR (RCC->APB1ENR1)
#define MODBUS_MASTER_TIMER_CLK_EN (RCC_APB1ENR1_TIM7EN)
#define MODBUS_MASTER_TIMER_CLK_FREQ 64000000UL
#define MODBUS_MASTER_TIMER_IRQN TIM7_DAC_IRQn
#define MODBUS_MASTER_TIMER_IRQHandler TIM7_DAC_IRQHandler
#define MODBUS_MASTER_TIMER_IRQ_PRIORITY 10
