/**
 * @file modbus_slave_driver_config_usart2.h
 * @author niwciu (niwciu@gmail.com)
 * @brief Header file with defines that speed up modbus slave driver configuration
 *        specially when porting driver to different USARTs and Timers.
 *        STM32G474RE — USART2 variant.
 *        USART2: PA2=TX (AF7), PA3=RX (AF7), PA1=DE (AF7)
 *        TIM15: APB2
 *        DMA1_Channel2 via DMAMUX1_Channel1, USART2_TX resource=26

 * @version 0.0.1
 * @date 2025-08-31
 *
 * @copyright Copyright (c) 2025
 *
 */
#pragma once

#include "stm32g474xx.h"

#define OFF 0
#define ON 1
#define LOW 0
#define HIGH 1

#define SLAVE_USE_DMA ON
#define SLAVE_USART_DE_HW_CONTROLL ON

/** modbus USART configuration*/
#define MODBUS_SLAVE_USART (USART2)
#define MODBUS_SLAVE_USART_CLK APB1ENR1
#define MODBUS_SLAVE_USART_CLK_EN (RCC_APB1ENR1_USART2EN)
#define MODBUS_SLAVE_USART_CLK_FREQ 64000000UL
#define MODBUS_SLAVE_USART_IRQN USART2_IRQn
#define MODBUS_SLAVE_USART_IRQHandler USART2_IRQHandler
#define MODBUS_SLAVE_USART_IRQ_PRIORITY 10

#if SLAVE_USE_DMA == ON
#define MODBUS_SLAVE_DMA DMA1
#define MODBUS_SLAVE_DMA_IRQN DMA1_Channel2_IRQn
#define MODBUS_SLAVE_DMA_IRQHandler DMA1_Channel2_IRQHandler
#define MODBUS_SLAVE_DMA_chanel DMA1_Channel2
#define MODBUS_SLAVE_DMA_ISR_TCIF DMA_ISR_TCIF2
#define MODBUS_SLAVE_DMA_ISR_TEIF DMA_ISR_TEIF2

#define USART1_TX_RESOURCE 25
#define USART2_TX_RESOURCE 26
#define USART3_TX_RESOURCE 28
#define MODBUS_SLAVE_USART_TX_RESOURCE USART2_TX_RESOURCE

#define MODBUS_SLAVE_DMAMUX_Chanel (DMAMUX1_Channel1)

/** DMA clock on AHB1 (G474 differs from G070 AHBENR) */
#define MODBUS_SLAVE_DMA_CLK_REG AHB1ENR
#define MODBUS_SLAVE_DMA_CLK_EN  RCC_AHB1ENR_DMA1EN
#endif

/** GPIO ports — PA1/PA2/PA3 all on GPIOA */
#define MODBUS_SLAVE_USART_RX_TX_PORT (GPIOA)
#define MODBUS_SLAVE_USART_DE_PORT (GPIOA)


#define MODBUS_SLAVE_USART_RX_MODE (GPIO_MODER_MODE3_1) // af mode
#define MODBUS_SLAVE_USART_TX_MODE (GPIO_MODER_MODE2_1) // af mode
#if SLAVE_USART_DE_HW_CONTROLL == ON
#define MODBUS_SLAVE_USART_DE_MODE (GPIO_MODER_MODE1_1) // af mode
#else
#define MODBUS_SLAVE_USART_DE_MODE (GPIO_MODER_MODE1_0) // general purpose output mode
#endif

#define MODBUS_SLAVE_USART_RX_MODE_Msk (GPIO_MODER_MODE3)
#define MODBUS_SLAVE_USART_TX_MODE_Msk (GPIO_MODER_MODE2)
#define MODBUS_SLAVE_USART_DE_MODE_Msk (GPIO_MODER_MODE1)

/** AF register masks — PA1/PA2/PA3 in AFRL (pins 0-7) */
#define MODBUS_SLAVE_USART_RX_AF_Msk (GPIO_AFRL_AFSEL3)
#define MODBUS_SLAVE_USART_TX_AF_Msk (GPIO_AFRL_AFSEL2)
#if SLAVE_USART_DE_HW_CONTROLL == ON
#define MODBUS_SLAVE_USART_DE_AF_Msk (GPIO_AFRL_AFSEL1)
#endif

/** AF7 values for USART2 on PA1/PA2/PA3 */
#define MODBUS_SLAVE_USART_RX_AF (GPIO_AFRL_AFSEL3_0 | GPIO_AFRL_AFSEL3_1 | GPIO_AFRL_AFSEL3_2)
#define MODBUS_SLAVE_USART_TX_AF (GPIO_AFRL_AFSEL2_0 | GPIO_AFRL_AFSEL2_1 | GPIO_AFRL_AFSEL2_2)
#if SLAVE_USART_DE_HW_CONTROLL == ON
#define MODBUS_SLAVE_USART_DE_AF (GPIO_AFRL_AFSEL1_0 | GPIO_AFRL_AFSEL1_1 | GPIO_AFRL_AFSEL1_2)
#endif

/** All pins PA1/PA2/PA3 are in AFRL */
#define MODBUS_SLAVE_USART_RX_TX_AF_REG (LOW)
#if SLAVE_USART_DE_HW_CONTROLL == ON
#define MODBUS_SLAVE_USART_DE_AF_REG (LOW)
#endif

// additionaly defines for manual DE controll
#if SLAVE_USART_DE_HW_CONTROLL == OFF
#define MODBUS_SLAVE_USART_DE_PUPDR        GPIO_PUPDR_PUPD1_0
#define MODBUS_SLAVE_USART_DE_PUPDR_Msk    GPIO_PUPDR_PUPD1_Msk

#define MODBUS_SLAVE_USART_DE_RESET_PIN	GPIO_BSRR_BR1
#define MODBUS_SLAVE_USART_DE_SET_PIN		GPIO_BSRR_BS1
#endif

/** GPIO clock enable — G474 uses AHB2 for GPIO (vs G070 IOPENR) */
#define MODBUS_SLAVE_USART_GPIO_RX_TX_CLK_EN (RCC_AHB2ENR_GPIOAEN)
#define MODBUS_SLAVE_USART_GPIO_DE_CLK_EN (RCC_AHB2ENR_GPIOAEN)
#define MODBUS_SLAVE_GPIO_CLK_REG AHB2ENR


/** modbus Timer configuration*/
#define MODBUS_SLAVE_TIMER (TIM15)
#define MODBUS_SLAVE_TIMER_APBENR (RCC->APB2ENR)
#define MODBUS_SLAVE_TIMER_CLK_EN (RCC_APB2ENR_TIM15EN)
#define MODBUS_SLAVE_TIMER_CLK_FREQ 64000000UL
#define MODBUS_SLAVE_TIMER_IRQN TIM15_IRQn
#define MODBUS_SLAVE_TIMER_IRQHandler TIM15_IRQHandler
#define MODBUS_SLAVE_TIMER_IRQ_PRIORITY 10
