/**
 * @file modbus_slave_driver_config.h
 * @author niwciu (niwciu@gmail.com)
 * @brief Modbus slave driver hardware configuration for STM32G474RE BRIDGE.
 *        USART3: PB10=TX (AF7), PB11=RX (AF7), PB14=DE (AF7, HW control)
 *        TIM6:   APB1, IRQ shared with DAC — no conflict with master's TIM7
 * @version 1.0.0
 * @date 2025-08-31
 *
 * @copyright Copyright (c) 2025
 *
 */
#pragma once

#include "stm32g474xx.h"

#define OFF 0
#define ON  1
#define LOW  0
#define HIGH 1

#define SLAVE_USE_DMA              ON
#define SLAVE_USART_DE_HW_CONTROLL ON

/** USART3 — APB1, GPIO GPIOB */
#define MODBUS_SLAVE_USART          (USART3)
#define MODBUS_SLAVE_USART_CLK      APB1ENR1
#define MODBUS_SLAVE_USART_CLK_EN   (RCC_APB1ENR1_USART3EN)
#define MODBUS_SLAVE_USART_CLK_FREQ 64000000UL
#define MODBUS_SLAVE_USART_IRQN     USART3_IRQn
#define MODBUS_SLAVE_USART_IRQHandler USART3_IRQHandler
#define MODBUS_SLAVE_USART_IRQ_PRIORITY 10

/** GPIO ports for RX/TX (PB11/PB10) and DE (PB14) — same port GPIOB */
#define MODBUS_SLAVE_USART_RX_TX_PORT (GPIOB)
#define MODBUS_SLAVE_USART_DE_PORT    (GPIOB)

/** GPIO mode bits — AF mode (10b) for pins 10, 11, 14 */
#define MODBUS_SLAVE_USART_RX_MODE     (GPIO_MODER_MODE11_1) // PB11, AF mode
#define MODBUS_SLAVE_USART_TX_MODE     (GPIO_MODER_MODE10_1) // PB10, AF mode
#define MODBUS_SLAVE_USART_DE_MODE     (GPIO_MODER_MODE14_1) // PB14, AF mode

#define MODBUS_SLAVE_USART_RX_MODE_Msk (GPIO_MODER_MODE11)
#define MODBUS_SLAVE_USART_TX_MODE_Msk (GPIO_MODER_MODE10)
#define MODBUS_SLAVE_USART_DE_MODE_Msk (GPIO_MODER_MODE14)

/** AF register masks — PB10/PB11/PB14 are in AFRH (pins 8–15) */
#define MODBUS_SLAVE_USART_RX_AF_Msk   (GPIO_AFRH_AFSEL11)
#define MODBUS_SLAVE_USART_TX_AF_Msk   (GPIO_AFRH_AFSEL10)
#define MODBUS_SLAVE_USART_DE_AF_Msk   (GPIO_AFRH_AFSEL14)

/** AF7 values for USART3 on PB10/PB11/PB14 */
#define MODBUS_SLAVE_USART_RX_AF  (GPIO_AFRH_AFSEL11_0 | GPIO_AFRH_AFSEL11_1 | GPIO_AFRH_AFSEL11_2)
#define MODBUS_SLAVE_USART_TX_AF  (GPIO_AFRH_AFSEL10_0 | GPIO_AFRH_AFSEL10_1 | GPIO_AFRH_AFSEL10_2)
#define MODBUS_SLAVE_USART_DE_AF  (GPIO_AFRH_AFSEL14_0 | GPIO_AFRH_AFSEL14_1 | GPIO_AFRH_AFSEL14_2)

/** All three pins are in AFRH */
#define MODBUS_SLAVE_USART_RX_TX_AF_REG (HIGH)
#define MODBUS_SLAVE_USART_DE_AF_REG    (HIGH)

#if SLAVE_USE_DMA == ON
#define MODBUS_SLAVE_DMA            DMA1
#define MODBUS_SLAVE_DMA_IRQN       DMA1_Channel2_IRQn
#define MODBUS_SLAVE_DMA_IRQHandler DMA1_Channel2_IRQHandler
#define MODBUS_SLAVE_DMA_chanel     DMA1_Channel2
#define MODBUS_SLAVE_DMA_ISR_TCIF   DMA_ISR_TCIF2
#define MODBUS_SLAVE_DMA_ISR_TEIF   DMA_ISR_TEIF2

/** DMAMUX1_Channel1 drives DMA1_Channel2; USART3_TX request ID = 28 */
#define MODBUS_SLAVE_USART_TX_RESOURCE 28
#define MODBUS_SLAVE_DMAMUX_Chanel  (DMAMUX1_Channel1)

/** DMA clock on AHB1 */
#define MODBUS_SLAVE_DMA_CLK_REG    AHB1ENR
#define MODBUS_SLAVE_DMA_CLK_EN     RCC_AHB1ENR_DMA1EN
#endif

/** GPIO clock enable — G474 uses AHB2 for GPIO */
#define MODBUS_SLAVE_USART_GPIO_RX_TX_CLK_EN (RCC_AHB2ENR_GPIOBEN)
#define MODBUS_SLAVE_USART_GPIO_DE_CLK_EN    (RCC_AHB2ENR_GPIOBEN)
#define MODBUS_SLAVE_GPIO_CLK_REG             AHB2ENR

/** TIM6 — APB1, IRQ shared with DAC */
#define MODBUS_SLAVE_TIMER          (TIM6)
#define MODBUS_SLAVE_TIMER_APBENR   (RCC->APB1ENR1)
#define MODBUS_SLAVE_TIMER_CLK_EN   (RCC_APB1ENR1_TIM6EN)
#define MODBUS_SLAVE_TIMER_CLK_FREQ 64000000UL
#define MODBUS_SLAVE_TIMER_IRQN     TIM6_DAC_IRQn
#define MODBUS_SLAVE_TIMER_IRQHandler TIM6_DAC_IRQHandler
#define MODBUS_SLAVE_TIMER_IRQ_PRIORITY 10
