/**
 * @file modbus_driver_config.h
 * @author niwciu (niwciu@gmail.com)
 * @brief Header file with defines that speed up modbus driver configuration specially when porting driver to different USARTs and Timers

 * @version 0.0.1
 * @date 2024-05-24
 *
 * @copyright Copyright (c) 2024
 *
 */
#pragma once

#include "stm32g070xx.h"

#define OFF 0
#define ON 1
#define LOW 0
#define HIGH 1

#define SLAVE_USE_DMA ON 
#define SLAVE_USART_DE_HW_CONTROLL ON

/** modbus USART configuration*/
#define MODBUS_SLAVE_USART (USART1)
#define MODBUS_SLAVE_USART_CLK APBENR2
#define MODBUS_SLAVE_USART_CLK_EN (RCC_APBENR2_USART1EN)
#define MODBUS_SLAVE_USART_CLK_FREQ 64000000UL
#define MODBUS_SLAVE_USART_IRQN USART1_IRQn
#define MODBUS_SLAVE_USART_IRQHandler USART1_IRQHandler
#define MODBUS_SLAVE_USART_IRQ_PRIORITY 10

#if SLAVE_USE_DMA == ON
#define MODBUS_SLAVE_DMA DMA1
#define MODBUS_SLAVE_DMA_IRQN DMA1_Channel2_3_IRQn
#define MODBUS_SLAVE_DMA_IRQHandler DMA1_Channel2_3_IRQHandler
#define MODBUS_SLAVE_DMA_chanel DMA1_Channel3
#define MODBUS_SLAVE_DMA_ISR_TCIF DMA_ISR_TCIF3
#define MODBUS_SLAVE_DMA_ISR_TEIF DMA_ISR_TEIF3

#define USART2_TX_RESOURCE 53
#define USART1_TX_RESOURCE 51
#define MODBUS_SLAVE_USART_TX_RESOURCE USART1_TX_RESOURCE

#define MODBUS_SLAVE_DMAMUX_Chanel (DMAMUX1_Channel2)
#endif

#define MODBUS_SLAVE_USART_RX_TX_PORT (GPIOB)
#define MODBUS_SLAVE_USART_DE_PORT (GPIOB)


#define MODBUS_SLAVE_USART_RX_MODE (GPIO_MODER_MODE7_1) // af mode
#define MODBUS_SLAVE_USART_TX_MODE (GPIO_MODER_MODE6_1) // af mode
#if SLAVE_USART_DE_HW_CONTROLL == ON
#define MODBUS_SLAVE_USART_DE_MODE (GPIO_MODER_MODE3_1) // af mode
#else
#define MODBUS_SLAVE_USART_DE_MODE (GPIO_MODER_MODE3_0) // general purpose output mode
#endif

#define MODBUS_SLAVE_USART_RX_MODE_Msk (GPIO_MODER_MODE7)
#define MODBUS_SLAVE_USART_TX_MODE_Msk (GPIO_MODER_MODE6)
#define MODBUS_SLAVE_USART_DE_MODE_Msk (GPIO_MODER_MODE3)

#define MODBUS_SLAVE_USART_RX_AF_Msk (GPIO_AFRL_AFSEL7)
#define MODBUS_SLAVE_USART_TX_AF_Msk (GPIO_AFRL_AFSEL6)
#if SLAVE_USART_DE_HW_CONTROLL == ON
#define MODBUS_SLAVE_USART_DE_AF_Msk (GPIO_AFRL_AFSEL3) 
#endif

#define MODBUS_SLAVE_USART_RX_AF (0)
#define MODBUS_SLAVE_USART_TX_AF (0)
#define MODBUS_SLAVE_USART_DE_AF (GPIO_AFRL_AFSEL3_2) //not needed for DE  controlled maually

//#define MODBUS_SLAVE_USART_AF_REG (LOW)
#define MODBUS_SLAVE_USART_RX_TX_AF_REG (LOW)
#if SLAVE_USART_DE_HW_CONTROLL == ON
#define MODBUS_SLAVE_USART_DE_AF_REG (LOW)  
#endif

// additionaly defines for manual DE controll
#if SLAVE_USART_DE_HW_CONTROLL == OFF
#define MODBUS_SLAVE_USART_DE_PUPDR        GPIO_PUPDR_PUPD3_0
#define MODBUS_SLAVE_USART_DE_PUPDR_Msk    GPIO_PUPDR_PUPD3_Msk

#define MODBUS_SLAVE_USART_DE_RESET_PIN	GPIO_BSRR_BR3
#define MODBUS_SLAVE_USART_DE_SET_PIN		GPIO_BSRR_BS3
#endif

//#define MODBUS_SLAVE_USART_GPIO_CLK_EN (RCC_IOPENR_GPIOBEN)
#define MODBUS_SLAVE_USART_GPIO_RX_TX_CLK_EN (RCC_IOPENR_GPIOBEN)
#define MODBUS_SLAVE_USART_GPIO_DE_CLK_EN (RCC_IOPENR_GPIOBEN)


/** modbus Timer configuration*/
#define MODBUS_SLAVE_TIMER (TIM15)
#define MODBUS_SLAVE_TIMER_APBENR (RCC->APBENR2)
#define MODBUS_SLAVE_TIMER_CLK_EN (RCC_APBENR2_TIM15EN)
#define MODBUS_SLAVE_TIMER_CLK_FREQ 64000000UL
#define MODBUS_SLAVE_TIMER_IRQN TIM15_IRQn
#define MODBUS_SLAVE_TIMER_IRQHandler TIM15_IRQHandler
#define MODBUS_SLAVE_TIMER_IRQ_PRIORITY 10
