/**
 * @file modbus_slave_driver_config_usart4.h
 * @author niwciu (niwciu@gmail.com)
 * @brief Header file with defines that speed up modbus slave driver configuration
 *        specially when porting driver to different USARTs and Timers.
 *        STM32G070R — USART4 variant.
 *        USART4: PA0=TX (AF4), PA1=RX (AF4), PB3=DE (AF4)
 *        TIM15: APB2
 *        DMA1_Channel4 via DMAMUX1_Channel3, USART4_TX resource=57
 *        NOTE: USART3 and USART4 share IRQ (USART3_4_IRQHandler). If only one
 *        is used in the project the handler dispatches to a single USART.
 *        NOTE: DMA1_Channel4 IRQ is shared (DMA1_Ch4_7_DMAMUX1_OVR_IRQHandler).

 * @version 0.0.1
 * @date 2025-08-31
 *
 * @copyright Copyright (c) 2025
 *
 */
#pragma once

#include "stm32g070xx.h"

#define OFF 0
#define ON 1
#define LOW 0
#define HIGH 1

#define SLAVE_USE_DMA ON
#define SLAVE_USART_DE_HW_CONTROLL ON

/** modbus USART configuration*/
#define MODBUS_SLAVE_USART (USART4)
#define MODBUS_SLAVE_USART_CLK APBENR1
#define MODBUS_SLAVE_USART_CLK_EN (RCC_APBENR1_USART4EN)
#define MODBUS_SLAVE_USART_CLK_FREQ 64000000UL
#define MODBUS_SLAVE_USART_IRQN USART3_4_IRQn
#define MODBUS_SLAVE_USART_IRQHandler USART3_4_IRQHandler
#define MODBUS_SLAVE_USART_IRQ_PRIORITY 10

#if SLAVE_USE_DMA == ON
#define MODBUS_SLAVE_DMA DMA1
#define MODBUS_SLAVE_DMA_IRQN DMA1_Ch4_7_DMAMUX1_OVR_IRQn
#define MODBUS_SLAVE_DMA_IRQHandler DMA1_Ch4_7_DMAMUX1_OVR_IRQHandler
#define MODBUS_SLAVE_DMA_chanel DMA1_Channel4
#define MODBUS_SLAVE_DMA_ISR_TCIF DMA_ISR_TCIF4
#define MODBUS_SLAVE_DMA_ISR_TEIF DMA_ISR_TEIF4

#define USART1_TX_RESOURCE 51
#define USART2_TX_RESOURCE 53
#define USART3_TX_RESOURCE 55
#define USART4_TX_RESOURCE 57
#define MODBUS_SLAVE_USART_TX_RESOURCE USART4_TX_RESOURCE

#define MODBUS_SLAVE_DMAMUX_Chanel (DMAMUX1_Channel3)
#endif

/** GPIO ports — PA0/PA1 on GPIOA, PB3 (DE) on GPIOB */
#define MODBUS_SLAVE_USART_RX_TX_PORT (GPIOA)
#define MODBUS_SLAVE_USART_DE_PORT (GPIOB)


#define MODBUS_SLAVE_USART_RX_MODE (GPIO_MODER_MODE1_1) // af mode
#define MODBUS_SLAVE_USART_TX_MODE (GPIO_MODER_MODE0_1) // af mode
#if SLAVE_USART_DE_HW_CONTROLL == ON
#define MODBUS_SLAVE_USART_DE_MODE (GPIO_MODER_MODE3_1) // af mode
#else
#define MODBUS_SLAVE_USART_DE_MODE (GPIO_MODER_MODE3_0) // general purpose output mode
#endif

#define MODBUS_SLAVE_USART_RX_MODE_Msk (GPIO_MODER_MODE1)
#define MODBUS_SLAVE_USART_TX_MODE_Msk (GPIO_MODER_MODE0)
#define MODBUS_SLAVE_USART_DE_MODE_Msk (GPIO_MODER_MODE3)

/** AF register masks — PA0/PA1 in AFRL, PB3 in AFRL */
#define MODBUS_SLAVE_USART_RX_AF_Msk (GPIO_AFRL_AFSEL1)
#define MODBUS_SLAVE_USART_TX_AF_Msk (GPIO_AFRL_AFSEL0)
#if SLAVE_USART_DE_HW_CONTROLL == ON
#define MODBUS_SLAVE_USART_DE_AF_Msk (GPIO_AFRL_AFSEL3)
#endif

/** AF4 values for USART4 on PA0/PA1/PB3 */
#define MODBUS_SLAVE_USART_RX_AF (GPIO_AFRL_AFSEL1_2)
#define MODBUS_SLAVE_USART_TX_AF (GPIO_AFRL_AFSEL0_2)
#if SLAVE_USART_DE_HW_CONTROLL == ON
#define MODBUS_SLAVE_USART_DE_AF (GPIO_AFRL_AFSEL3_2)
#endif

/** PA0/PA1 in AFRL, PB3 (DE) in AFRL */
#define MODBUS_SLAVE_USART_RX_TX_AF_REG (LOW)
#if SLAVE_USART_DE_HW_CONTROLL == ON
#define MODBUS_SLAVE_USART_DE_AF_REG (LOW)
#endif

// additionaly defines for manual DE controll
#if SLAVE_USART_DE_HW_CONTROLL == OFF
#define MODBUS_SLAVE_USART_DE_PUPDR        GPIO_PUPDR_PUPD3_0
#define MODBUS_SLAVE_USART_DE_PUPDR_Msk    GPIO_PUPDR_PUPD3_Msk

#define MODBUS_SLAVE_USART_DE_RESET_PIN	GPIO_BSRR_BR3
#define MODBUS_SLAVE_USART_DE_SET_PIN		GPIO_BSRR_BS3
#endif

//#define MODBUS_SLAVE_USART_GPIO_CLK_EN (RCC_IOPENR_GPIOAEN)
#define MODBUS_SLAVE_USART_GPIO_RX_TX_CLK_EN (RCC_IOPENR_GPIOAEN)
#define MODBUS_SLAVE_USART_GPIO_DE_CLK_EN (RCC_IOPENR_GPIOBEN)


/** modbus Timer configuration*/
#define MODBUS_SLAVE_TIMER (TIM15)
#define MODBUS_SLAVE_TIMER_APBENR (RCC->APBENR2)
#define MODBUS_SLAVE_TIMER_CLK_EN (RCC_APBENR2_TIM15EN)
#define MODBUS_SLAVE_TIMER_CLK_FREQ 64000000UL
#define MODBUS_SLAVE_TIMER_IRQN TIM15_IRQn
#define MODBUS_SLAVE_TIMER_IRQHandler TIM15_IRQHandler
#define MODBUS_SLAVE_TIMER_IRQ_PRIORITY 10
