/**
 * @file modbus_driver_config.h
 * @author niwciu (niwciu@gmail.com)
 * @brief Header file with defines that speed up modbus driver configuration
 *        specially when porting driver to different USARTs and Timers.
 * @version 1.0.0
 * @date 2025-08-31
 *
 * @copyright Copyright (c) 2025
 *
 */
#pragma once

#include "stm32g070xx.h"

#define OFF 0
#define ON 1
#define LOW 0
#define HIGH 1

#define SLAVE_USE_DMA OFF
#define SLAVE_USART_DE_HW_CONTROLL ON

/** modbus USART configuration — USART2, GPIOA: PA2=TX(AF1), PA3=RX(AF1), PA1=DE(AF1) */
#define MODBUS_SLAVE_USART (USART2)
#define MODBUS_SLAVE_USART_CLK APBENR1
#define MODBUS_SLAVE_USART_CLK_EN (RCC_APBENR1_USART2EN)
#define MODBUS_SLAVE_USART_CLK_FREQ 64000000UL
#define MODBUS_SLAVE_USART_IRQN USART2_IRQn
#define MODBUS_SLAVE_USART_IRQHandler USART2_IRQHandler
#define MODBUS_SLAVE_USART_IRQ_PRIORITY 10

#define MODBUS_SLAVE_USART_RX_TX_PORT (GPIOA)
#define MODBUS_SLAVE_USART_DE_PORT (GPIOA)

#define MODBUS_SLAVE_USART_RX_MODE (GPIO_MODER_MODE3_1) // PA3, AF mode
#define MODBUS_SLAVE_USART_TX_MODE (GPIO_MODER_MODE2_1) // PA2, AF mode
#if SLAVE_USART_DE_HW_CONTROLL == ON
#define MODBUS_SLAVE_USART_DE_MODE (GPIO_MODER_MODE1_1) // PA1, AF mode
#else
#define MODBUS_SLAVE_USART_DE_MODE (GPIO_MODER_MODE1_0) // PA1, output mode
#endif

#define MODBUS_SLAVE_USART_RX_MODE_Msk (GPIO_MODER_MODE3)
#define MODBUS_SLAVE_USART_TX_MODE_Msk (GPIO_MODER_MODE2)
#define MODBUS_SLAVE_USART_DE_MODE_Msk (GPIO_MODER_MODE1)

#define MODBUS_SLAVE_USART_RX_AF_Msk (GPIO_AFRL_AFSEL3)
#define MODBUS_SLAVE_USART_TX_AF_Msk (GPIO_AFRL_AFSEL2)
#if SLAVE_USART_DE_HW_CONTROLL == ON
#define MODBUS_SLAVE_USART_DE_AF_Msk (GPIO_AFRL_AFSEL1)
#endif

#define MODBUS_SLAVE_USART_RX_AF (GPIO_AFRL_AFSEL3_0) // AF1
#define MODBUS_SLAVE_USART_TX_AF (GPIO_AFRL_AFSEL2_0) // AF1
#if SLAVE_USART_DE_HW_CONTROLL == ON
#define MODBUS_SLAVE_USART_DE_AF (GPIO_AFRL_AFSEL1_0) // AF1
#endif

#define MODBUS_SLAVE_USART_RX_TX_AF_REG (LOW)
#if SLAVE_USART_DE_HW_CONTROLL == ON
#define MODBUS_SLAVE_USART_DE_AF_REG (LOW)
#endif

// additional defines for manual DE control
#if SLAVE_USART_DE_HW_CONTROLL == OFF
#define MODBUS_SLAVE_USART_DE_PUPDR     GPIO_PUPDR_PUPD1_0
#define MODBUS_SLAVE_USART_DE_PUPDR_Msk GPIO_PUPDR_PUPD1_Msk
#define MODBUS_SLAVE_USART_DE_RESET_PIN GPIO_BSRR_BR1
#define MODBUS_SLAVE_USART_DE_SET_PIN   GPIO_BSRR_BS1
#endif

#define MODBUS_SLAVE_USART_GPIO_RX_TX_CLK_EN (RCC_IOPENR_GPIOAEN)
#define MODBUS_SLAVE_USART_GPIO_DE_CLK_EN (RCC_IOPENR_GPIOAEN)

/** modbus Timer configuration — TIM7 */
#define MODBUS_SLAVE_TIMER (TIM7)
#define MODBUS_SLAVE_TIMER_APBENR (RCC->APBENR1)
#define MODBUS_SLAVE_TIMER_CLK_EN (RCC_APBENR1_TIM7EN)
#define MODBUS_SLAVE_TIMER_CLK_FREQ 64000000UL
#define MODBUS_SLAVE_TIMER_IRQN TIM7_IRQn
#define MODBUS_SLAVE_TIMER_IRQHandler TIM7_LPTIM2_IRQHandler
#define MODBUS_SLAVE_TIMER_IRQ_PRIORITY 10
