/**
 * @file modbus_driver_config.h
 * @author niwciu (niwciu@gmail.com)
 * @brief Header file with defines that speed up modbus driver configuration specially when porting driver to different USARTs and Timers

 * @version 0.0.1
 * @date 2024-05-24
 *
 * @copyright Copyright (c) 2024
 *
 */
#pragma once

#include "stm32g070xx.h"

#define OFF 0
#define ON 1
#define LOW 0
#define HIGH 1

#define MASTER_USE_DMA OFF
#define USART_DE_HW_CONTROLL ON

/** modbus USART configuration*/
#define MODBUS_MASTER_USART (USART1)
#define MODBUS_MASTER_USART_CLK APBENR2
#define MODBUS_MASTER_USART_CLK_EN (RCC_APBENR2_USART1EN)
#define MODBUS_MASTER_USART_CLK_FREQ 64000000UL
#define MODBUS_MASTER_USART_IRQN USART1_IRQn
#define MODBUS_MASTER_USART_IRQHandler USART1_IRQHandler
#define MODBUS_MASTER_USART_IRQ_PRIORITY 10

#if MASTER_USE_DMA == ON
#define MODBUS_MASTER_DMA DMA1
#define MODBUS_MASTER_DMA_IRQN DMA1_Channel2_3_IRQn
#define MODBUS_MASTER_DMA_IRQHandler DMA1_Channel2_3_IRQHandler
#define MODBUS_MASTER_DMA_chanell DMA1_Channel2
#define MODBUS_MASTER_DMA_ISR_TCIF DMA_ISR_TCIF2
#define MODBUS_MASTER_DMA_ISR_TEIF DMA_ISR_TEIF2

#define USART2_TX_RESOURCE 53
#define USART1_TX_RESOURCE 51
#define MODBUS_MASTER_USART_TX_RESOURCE USART1_TX_RESOURCE
#endif

#define MODBUS_MASTER_USART_RX_TX_PORT (GPIOB)
#define MODBUS_MASTER_USART_DE_PORT (GPIOB)


#define MODBUS_MASTER_USART_RX_MODE (GPIO_MODER_MODE7_1) // af mode
#define MODBUS_MASTER_USART_TX_MODE (GPIO_MODER_MODE6_1) // af mode
#if USART_DE_HW_CONTROLL == ON
#define MODBUS_MASTER_USART_DE_MODE (GPIO_MODER_MODE3_1) // af mode
#else
#define MODBUS_MASTER_USART_DE_MODE (GPIO_MODER_MODE3_0) // general purpose output mode
#endif

#define MODBUS_MASTER_USART_RX_MODE_Msk (GPIO_MODER_MODE7)
#define MODBUS_MASTER_USART_TX_MODE_Msk (GPIO_MODER_MODE6)
#define MODBUS_MASTER_USART_DE_MODE_Msk (GPIO_MODER_MODE3)

#define MODBUS_MASTER_USART_RX_AF_Msk (GPIO_AFRL_AFSEL7)
#define MODBUS_MASTER_USART_TX_AF_Msk (GPIO_AFRL_AFSEL6)
#if USART_DE_HW_CONTROLL == ON
#define MODBUS_MASTER_USART_DE_AF_Msk (GPIO_AFRL_AFSEL3) 
#endif

#define MODBUS_MASTER_USART_RX_AF (0)
#define MODBUS_MASTER_USART_TX_AF (0)
#define MODBUS_MASTER_USART_DE_AF (GPIO_AFRL_AFSEL3_2) //not needed for DE  controlled maually

//#define MODBUS_MASTER_USART_AF_REG (LOW)
#define MODBUS_MASTER_USART_RX_TX_AF_REG (LOW)
#if USART_DE_HW_CONTROLL == ON
#define MODBUS_MASTER_USART_DE_AF_REG (LOW)  
#endif

// additionaly defines for manual DE controll
#if USART_DE_HW_CONTROLL == OFF
#define MODBUS_MASTER_USART_DE_RESET_PIN	GPIO_BSRR_BR3
#define MODBUS_MASTER_USART_DE_SET_PIN		GPIO_BSRR_BS3
#endif

//#define MODBUS_MASTER_USART_GPIO_CLK_EN (RCC_IOPENR_GPIOBEN)
#define MODBUS_MASTER_USART_GPIO_RX_TX_CLK_EN (RCC_IOPENR_GPIOBEN)
#define MODBUS_MASTER_USART_GPIO_DE_CLK_EN (RCC_IOPENR_GPIOBEN)


/** modbus Timer configuration*/
#define MODBUS_MASTER_TIMER (TIM7)
#define MODBUS_MASTER_TIMER_CLK_EN (RCC_APBENR1_TIM7EN)
#define MODBUS_MASTER_TIMER_CLK_FREQ 64000000UL
#define MODBUS_MASTER_TIMER_IRQN TIM7_IRQn
#define MODBUS_MASTER_TIMER_IRQHandler TIM7_LPTIM2_IRQHandler
#define MODBUS_MASTER_TIMER_IRQ_PRIORITY 10
