/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#include "core_init.h"
#include "modbus_driver_interface.h"
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint8_t test_buf[]={"hello world !!!\r\n"};
uint8_t test_buf_2[]={"test !!!\r\n"};

const struct modbus_RTU_driver_struct *driver=NULL;

int main(void)
{
  core_init();
  driver=get_RTU_driver_interface();
  driver->init(921600,ODD);

  __enable_irq();
  driver->send(test_buf,sizeof(test_buf));
  driver->enable_rcev();

    /* Loop forever */
	while(1)
  {

  }
}
